### ISSUE TITLE
internal mmc mount point 

### ISSUE THREAD

**Issue by kalawy** [noname8964/vold-posix#1]
the internal mmc mount point gets changed   just  after  the device  boots with a few seconds  ..  thus  all apps don't detect it   and a flood  of error messages  
it is still accessible from /data/media 
but not from /storage/emulated/0

that in magisk module v 1

**Comment by noname8964** [comment]
Which rom you are using? I didn't change the mount point. Maybe it's a restart vold issue, use v2.0 and try again.

**Comment by kalawy** [comment]
this problem solved on v2
