### ISSUE TITLE
Oreo 8.0 Support

### ISSUE THREAD

**Issue by hy-l** [noname8964/vold-posix#3]
hi,

I'm using Samsung's stock ROM (Oreo 8.0) on my Galaxy S8, and a customized kernel by myself. I've enabled NTFS (even HFS+) in-kernel support, and I can mount disks that formatted with these filesystems in terminal. But I have no idea how to make Android system accept these. Then I found this module, but unfortunately it can't be installed on 8.0 system. 

Could you please also add 8.0 support? Thank you!

**Comment by noname8964** [comment]
idk if samsung rom can use this. and my vold is compile from AOSP 8.1 r47, this maybe not work with AOSP 8.0. you can download the module and remove the system api check in installer script then try it. I can't promise anything for that.

**Comment by noname8964** [comment]
I test it on my nokia phone. Nexus and Pixel stock rom can work, maybe sony stock rom also. Haven't used Samsung before.

**Comment by noname8964** [comment]
Only add a .rc scrpit and my own magiskinit to the boot image. since you can use official magisk, so I think this isn't the problem. maybe you can try to compile with AOSP 8.0 source tree.
BTW, galaxy s8 seems has 8.1 rom, maybe you can try that.

PS: filesystem support except f2fs is useless in this module. ntfs and exfat will fall back to use fuse driver which is a userspace filesystem driver.

**Comment by hy-l** [comment]
no, samsung hasn't officially provided 8.1 rom for galaxy s8, though i'm not sure about customized ones. but i won't expect to find custom roms for my variant (sm-g9500), since it's not widely used. and that's why i tried to compile kernel by myself.

as what i've said, my kernel itself has ntfs support (exfat is already supported by the stock system)

> dreamqlte:/data/ssh/root # cat /proc/filesystems
nodev   sysfs
nodev   rootfs
nodev   tmpfs
nodev   bdev
nodev   proc
nodev   cpuset
nodev   cgroup
nodev   cgroup2
nodev   configfs
nodev   debugfs
nodev   tracefs
nodev   sockfs
nodev   pipefs
nodev   ramfs
nodev   devpts
        ext3
        ext4
nodev   sdcardfs
        ext2
        vfat
        msdos
        sdfat
        hfsplus
        hfs
nodev   ecryptfs
        ntfs
        fuseblk
nodev   fuse
nodev   fusectl
nodev   overlay
nodev   pstore
nodev   selinuxfs
nodev   functionfs

and i can mount a partition with `mount -t FS DEV DIR` directly. all i want for now, is that the system can do this process automatically for any newly added devices (sdcards, OTG devices, etc). in other words, it may need another type of modified vold to implement these... apparently i chose the wrong place to talk about this (i suddenly realized). sorry about that.
